export const games = [
  {
    key: "snake",
    name: "Koko Snake",
    image: "/images/kokosnake.jpg",
    link: "#",
    page: "/game/snake",
    type: "Games",
    webtype: "nextjs",
    category: "games",
  },
  {
    key: "flappy",
    name: "Flappy Kokomo",
    image: "/images/flappykokomo.png",
    link: "#",
    page: "/game/flappy",
    type: "Games",
    webtype: "nextjs",
    category: "games",
    isNew: true,
  },
  {
    key: "chess",
    name: "Koko Chess",
    image: "/images/ChessSet.jpg",
    link: "#",
    page: "/game/chess",
    type: "Games",
    webtype: "nextjs",
    category: "games",
    isNew: true,
  },
  {
    key: "tetris",
    name: "Tetris",
    image: "/images/tetris.png",
    link: "#",
    page: "/game/tetris",
    type: "Games",
    webtype: "nextjs",
    category: "games",
    isNew: true,
  },
  {
    key: "onemillion",
    name: "One Milion",
    image: "/images/kokomogame.png",
    link: "#",
    page: "/game/onemillion",
    type: "Games",
    webtype: "unity",
    category: "games",
  },

  // rewards
  {
    key: "1m1",
    name: "Daily Claim",
    image: "/images/dailyclaim.png",
    link: "#",
    page: "claim",
    type: "Rewards",
    category: "rewards",
    webtype: "nextjs",
  },
  {
    key: "raffle",
    name: "Koko Raffle",
    image: "/images/rafflegame.jpeg",
    link: "#",
    page: "raffle",
    type: "Rewards",
    category: "rewards",
    webtype: "nextjs",
    number: 3,
  },
  {
    key: "spin",
    name: "Koko Spin",
    image: "/images/spingame.png",
    link: "#",
    page: "spinner",
    type: "Rewards",
    category: "rewards",
    webtype: "nextjs",
  },
];
