import type { Metadata, Viewport } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { cn } from "./_lib/utils";
import { bumperStickerFont, madeTommySoftFont } from "./_lib/fonts";
import { Suspense } from "react";
import Script from "next/script";
import { ThirdwebProvider } from "thirdweb/react";
import { AppProvider } from "./_contexts/appContext";
import { ThirdWeb } from "./_providers/thirdWebProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <Script id="focus-visible-polyfill" strategy="beforeInteractive">
          {`
            document.documentElement.classList.remove('js-focus-visible');
            document.documentElement.removeAttribute('data-js-focus-visible');
          `}
        </Script>
      </head>
      <body
        className={cn(
          "font-made-tommy",
          bumperStickerFont.variable,
          madeTommySoftFont.variable
        )}
      >
        <Suspense fallback={<></>}>
          <ThirdwebProvider>
            <AppProvider>
              <ThirdWeb>
                {children}
                <Toaster
                  position="top-center"
                  toastOptions={{ duration: 2000 }}
                />
              </ThirdWeb>
            </AppProvider>
          </ThirdwebProvider>
        </Suspense>
      </body>
    </html>
  );
}
