import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { cn } from "./_lib/utils";
import { bumperStickerFont, madeTommySoftFont } from "./_lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "font-made-tommy",
          bumperStickerFont.variable,
          madeTommySoftFont.variable
        )}
      >
        {children}
        <Toaster position="top-center" toastOptions={{ duration: 2000 }} />
      </body>
    </html>
  );
}
