import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { cn } from "./_lib/utils";
import { bumperStickerFont, madeTommySoftFont } from "./_lib/fonts";
import { Suspense } from "react";
import Script from "next/script";
import { AppProvider } from "./_contexts/appContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <Script id="focus-visible-polyfill" strategy="beforeInteractive">
          {`
            document.documentElement.classList.remove('js-focus-visible');
            document.documentElement.removeAttribute('data-js-focus-visible');
          `}
        </Script>
      </head>
      <body
        className={cn(
          "font-made-tommy",
          bumperStickerFont.variable,
          madeTommySoftFont.variable
        )}
      >
        <AppProvider>
          <Suspense fallback={<></>}>{children}</Suspense>
          <Toaster position="top-center" toastOptions={{ duration: 2000 }} />
        </AppProvider>
      </body>
    </html>
  );
}
